### ISSUE TITLE
Simulation models for rtl_hard

### ISSUE THREAD

**Issue by hema0730** [black-parrot-examples/bsg_tapeout_v1_tsmc40#3]
It seems like the simulation of rtl_hard doesn't really use soft and hard IP models to replace correspondent RTL models which will makes bugs harder to find if they are hidden in files such as those in basejump_stl/hard.
[https://github.com/black-parrot-examples/bsg_tapeout_v1_tsmc40/blob/master/toplevels/bsg_ac_black_parrot_quad_core_rc3/testing/rtl_hard/bsg_config.tcl](url)

**Comment by dpetrisko** [comment]
Whoops! Will fix

**Comment by hema0730** [comment]
Resolved.
